export const themes = {
  forest: {
    name: "森林绿",
    primary: "#2D6A4F",
    secondary: "#95D5B2",
    background: "#D8F3DC",
    accent: "#40916C",
    text: "#081C15",
    lightText: "#52B788",
    border: "#95D5B2",
    buttonText: "#FFFFFF",
  },
  elegant: {
    name: "优雅紫",
    primary: "#7B2CBF",
    secondary: "#C77DFF",
    background: "#E0AAFF",
    accent: "#9D4EDD",
    text: "#3C096C",
    lightText: "#9D4EDD",
    border: "#C77DFF",
    buttonText: "#FFFFFF",
  },
  sakura: {
    name: "樱花粉",
    primary: "#FF69B4",
    secondary: "#FFB6C1",
    background: "#FFF0F5",
    accent: "#FF1493",
    text: "#4A4E69",
    lightText: "#9A8C98",
    border: "#FFB6C1",
    buttonText: "#FFFFFF",
  },
  cyan: {
    name: "青碧",
    primary: "#2A9D8F",
    secondary: "#89D5CF",
    background: "#E9F5F3",
    accent: "#264653",
    text: "#1A3C34",
    lightText: "#457B9D",
    border: "#89D5CF",
    buttonText: "#FFFFFF",
  },
  pharmaceutical: {
    name: "药剂师",
    primary: "#2196F3",
    secondary: "#03A9F4",
    background: "#E3F2FD",
    accent: "#FFC107",
    text: "#333333",
    lightText: "#666666",
    border: "#E0E0E0",
    buttonText: "#FFFFFF",
  },
  mathemagiker: {
    name: "数学魔法师",
    primary: "#07889B",
    secondary: "#66B9BF",
    background: "#F5F9FA",
    accent: "#E37222",
    text: "#2C3E50",
    lightText: "#607D8B",
    border: "#66B9BF",
    buttonText: "#FFFFFF",
  },
}

export type ThemeName = keyof typeof themes

